@startuml
 title Kjøp av bilforsikring
 hide footbox
 autonumber
 participant Klient
 participant Integrasjonslag as API
 participant "Fagsystem / Database" as Policy
 participant Brevtjeneste as Letter

 Klient -> API: Opprett avtale\nSkjemadata
 activate API
 API -> Policy: Opprett kunde\nKundeopplysninger
 activate Policy
 Policy --> API: Kundenummer
 deactivate Policy

 API -> Policy: Opprett avtale\nKundenummer og forsikringsopplysninger
 activate Policy
 Policy --> API: Avtalenummer
 deactivate Policy

 API -> Letter: Send avtale til kunde\nAvtalenummer og mottakeropplysninger
 activate Letter
 Letter --> API: Status på utsendelse
 deactivate Letter

 API -> Policy: Oppdater status til "avtale sendt"\nAvtalenummer
 activate Policy
 Policy --> API: Avtalestatus
 deactivate Policy

 API --> Klient: Avtalenummer og status
 deactivate API

@enduml